import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  en: {
    // Navigation & Tabs
    'dashboard': 'Dashboard',
    'customers': 'Customers',
    'agents': 'Agents',
    'staff': 'Staff',
    'projects': 'Projects',
    'data': 'Data',
    'checkinout': 'Check-in/Out',
    'boss': 'Boss',
    'trips': 'Trips',
    'trip_details': 'Trip Details',
    'expenses': 'Expenses',
    'transactions': 'Transactions',
    'sharing': 'Sharing',
    'reports': 'Reports',
    'settings': 'Settings',
    
    // Trip Management
    'project_management': 'Project Management',
    'back_to_trips': 'Back to Trips',
    'view_in': 'View in:',
    'total_rolling': 'Total Rolling',
    'total_win_loss': 'Total Win/Loss',
    'total_buy_in': 'Total Buy In',
    'total_buy_out': 'Total Buy Out',
    'net_result': 'Net Result',
    'total_expenses': 'Total Expenses',
    'active_customers': 'Active Customers',
    'recent_activity': 'Recent Activity',
    
    // Actions
    'refresh': 'Refresh',
    'add_new': 'Add New',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'close': 'Close',
    
    // Status
    'active': 'Active',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'cancelled': 'Cancelled',
    'pending': 'Pending',
    
    // Common
    'name': 'Name',
    'description': 'Description',
    'date': 'Date',
    'amount': 'Amount',
    'status': 'Status',
    'actions': 'Actions',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'no_data': 'No data available',
    
    // Currency
    'currency': 'Currency',
    'exchange_rate': 'Exchange Rate',
    'hkd': 'HKD',
    'myr': 'MYR',
    'peso': 'PESO',
    
    // Reports
    'reports_title': 'Real-time Reports Dashboard',
    'reports_subtitle': 'Comprehensive business intelligence and analytics',
    'overview_metrics': 'Overview Metrics',
    'financial_summary': 'Financial Summary',
    'customer_metrics': 'Customer Metrics',
    'agent_performance': 'Agent Performance',
    'operational_metrics': 'Operational Metrics',
    'agent_hierarchy': 'Agent Performance Hierarchy',
    'agent_hierarchy_desc': 'Hierarchical view of agents and their customers - expand to see customer details',
    'sort_by': 'Sort by:',
    'reports_total_rolling': 'Total Rolling',
    'win_loss': 'Win/Loss',
    'customer_count': 'Customer Count',
    'average_rolling': 'Average Rolling',
    'agent_name': 'Agent Name',
    'individual_rolling': 'Individual Rolling',
    'individual_win': 'Individual Win',
    'trip_count': 'Trip Count',
    'profit_loss': 'Profit/Loss',
    'house_gross_win': 'House Gross Win',
    'house_net_win': 'House Net Win',
    'house_final_profit': 'House Final Profit',
    'reports_total_customers': 'Total Customers',
    'reports_active_customers': 'Active Customers',
    'total_agents': 'Total Agents',
    'active_agents': 'Active Agents',
    'total_trips': 'Total Trips',
    'completed_trips': 'Completed Trips',
    'ongoing_trips': 'Ongoing Trips',
    'profit_margin': 'Profit Margin',
    'rolling_percentage': 'Rolling Percentage',
    'company_share': 'Company Share',
    'net_cash_flow': 'Net Cash Flow',
    'real_time_sync': 'Real-time Sync',
    'last_sync': 'Last Sync',
    'connection_status': 'Connection Status',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'sync_error': 'Sync Error',
    'auto_refresh': 'Auto Refresh',
    'manual_refresh': 'Manual Refresh',
    'export_data': 'Export Data',
    
    // Financial Overview
    'financial_overview': 'Real-time Financial Overview',
    'total_rolling_amount': 'Total Rolling Amount',
    'company_gross_profit': 'Company Gross Profit',
    'overview_expenses': 'Expenses',
    'company_net_profit': 'Company Net Profit',
    'from_rolling_records': 'From rolling records across customers',
    'from_trip_sharing': 'From trip sharing without data',
    'total_operational_expenses': 'Total operational expenses from trip sharing',
    'company_share_from_trip': 'Company share from trip sharing',
    
    // Operations Overview
    'operations_overview': 'Operations Overview',
    'overview_active_customers': 'Active Customers',
    'overview_active_agents': 'Active Agents',
    'overview_trip_summary': 'Trip Summary',
    'overview_recent_activity': 'Recent Activity',
    'of_total_customers': 'of total customers',
    'of_total_agents': 'of total agents',
    'completed_ongoing_planned': 'completed, ongoing, planned',
    'transactions_in_last_hours': 'Transactions in last 24 hours',
    
    // Active Trips
    'overview_active_trips': 'Active Trips',
    'current_ongoing_trips': 'Current ongoing trips with real-time performance data',
    'testing_trip': 'Testing Trip',
    'manila_okada': 'Manila Okada',
    'overview_progress': 'Progress',
    'overview_rolling': 'Rolling',
    'overview_win_loss': 'Win/Loss',
    
    // Customer Performance
    'customer_performance': 'Real-time Customer Performance',
    'all_customers_based_on': 'All customers based on live rolling data',
    'sort_by_rolling': 'Sort by: Rolling',
    'agent_active': 'Agent: • Active',
    'overview_commission_rate': 'Commission Rate',
    
    // Additional Common Terms
    'welcome_user': 'Welcome',
    'silver_vip': 'Silver',
    'gold_vip': 'Gold',
    'platinum_vip': 'Platinum',
    'diamond_vip': 'Diamond',
    
    // Dashboard specific terms
    'company_loss': 'Company Loss',
    'company_win': 'Company Win', 
    'break_even': 'Break Even',
    'agent': 'Agent',
    'unknown_destination': 'Unknown Destination',
    'progress': 'Progress',
    
    // Customer Management specific
    'update_customer_info': 'Update basic customer information',
    'add_customer_desc': 'Add a new customer with basic details. You can add extended details after creation.',
    'customer_full_name': 'Customer full name',
    'select_agent': 'Select an agent',
    'no_customers_found': 'No customers found',
    'contact_admin': 'Contact an administrator to add customers',
    'add_first_customer': 'Add your first customer to get started',
    'records': 'records',
    'live_data': 'Live Data',
    'customer_since': 'Customer since',
    'details_available': 'Details available',
    'no_details_available': 'No details available',
    'edit_basic_info': 'Edit Basic Info',
    'edit_details': 'Edit Details',
    'promote_to_agent': 'Promote to Agent',
    'delete_customer': 'Delete Customer',
    
    // Project Management specific
    'trips_loaded': 'Trips Loaded',
    'customers_available': 'Customers Available', 
    'agents_available': 'Agents Available',
    'create_trip': 'Create Trip',
    'create_new_trip': 'Create New Trip',
    'create_trip_desc': 'Create a new trip that will be saved to Supabase database.',
    'trip_name': 'Trip Name',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'creating': 'Creating...',
    'loading_trips': 'Loading trips...',
    'no_trips_found': 'No trips found',
    'view_details': 'View Details',
    'amount_hkd': 'Amount (HKD)',
    'buy_in': 'Buy-in',
    'buy_out': 'Buy-out',
    
    // Additional Project Management
    'trip_customers': 'Trip Customers',
    'add_customer': 'Add Customer',
    'add_customer_to_trip': 'Add Customer to Trip',
    'search_select_customers': 'Search and select from available customers',
    'search_customers': 'Search Customers',
    'search_by_name_email_agent': 'Search by name, email, or agent...',
    'showing_customers': 'Showing',
    'of_available_customers': 'of available customers',
    'add_first_customer_trip': 'Add First Customer',
    'no_customers_added': 'No customers added to this trip',
    'all_customers_added': 'All customers are already added to this trip',
    'no_customers_match_search': 'No customers match your search',
    'adding': 'Adding...',
    'add': 'Add',
    'deleting': 'Deleting...',
    'delete_customer_confirm': 'Delete Customer',
    'delete_customer_warning': 'Are you sure you want to remove this customer from the trip? This action cannot be undone.',
    'remove_from_trip': 'Remove from Trip',
    
    // Financial Terms
    'cash_out': 'Cash-out',
    'rolling': 'Rolling',
    'rolling_amount': 'Rolling Amount',
    'commission_earned': 'Commission Earned',
    'profit_sharing_rate': 'Profit Sharing Rate',
    'agent_profit_sharing': 'Agent Profit Sharing',
    'agent_summary': 'Agent Summary',
    'company_share_amount': 'Company Share',
    'agent_share_amount': 'Agent Share',
    'total_commission_amount': 'Total Commission',
    'total_profit_amount': 'Total Profit',
    'agent_profit_share_amount': 'Agent Profit Share',
    'customer_count_total': 'Customer Count',
    
    // Transaction Management
    'add_transaction': 'Add Transaction',
    'add_rolling': 'Add Rolling',
    'transaction_type': 'Transaction Type',
    'transaction_amount': 'Transaction Amount',
    'commission_rate': 'Commission Rate',
    'current_rate': 'Current rate',
    'commission': 'Commission',
    'game_type': 'Game Type',
    'venue': 'Venue',
    'date_time': 'Date & Time',
    'attachment': 'Attachment',
    'optional': 'Optional',
    'required': 'Required',
    'enter_amount': 'Enter amount',
    'select_game_type': 'Select game type',
    'enter_venue': 'Enter venue',
    'select_date_time': 'Select date and time',
    'upload_attachment': 'Upload attachment',
    
    // History and Records
    'transaction_history': 'Transaction History',
    'rolling_history': 'Rolling History',
    'no_transaction_history': 'No transaction history',
    'no_rolling_history': 'No rolling history',
    'edit_transaction': 'Edit Transaction',
    'edit_rolling': 'Edit Rolling',
    'delete_transaction': 'Delete Transaction',
    'delete_rolling': 'Delete Rolling',
    'confirm_delete_transaction': 'Are you sure you want to delete this transaction?',
    'confirm_delete_rolling': 'Are you sure you want to delete this rolling record?',
    
    // Photos and Attachments
    'photos': 'Photos',
    'view_customer_photos': 'View Customer Photos',
    'transaction_photos': 'Transaction Photos',
    'rolling_photos': 'Rolling Photos',
    'upload_photo': 'Upload Photo',
    'no_photos': 'No photos available',
    
    // VIP Levels
    'vip': 'VIP',
    'vip_level': 'VIP Level',
    'standard': 'Standard',
    'silver': 'Silver',
    'gold': 'Gold',
    'platinum': 'Platinum',
    'diamond': 'Diamond',
    
    // Profit Sharing
    'profit_sharing': 'Profit Sharing',
    'profit_sharing_information': 'Profit Sharing Information',
    'edit_profit_sharing': 'Edit Profit Sharing',
    'update_profit_sharing': 'Update Profit Sharing',
    'new_profit_sharing_rate': 'New Profit Sharing Rate',
    'current_profit_sharing_rate': 'Current Profit Sharing Rate',
    'projected_profit_share': 'Projected Profit Share',
    'rate_change_impact': 'Rate Change Impact',
    
    // Customer Details
    'edit_customer_details': 'Edit Customer Details',
    'update_comprehensive_info': 'Update comprehensive customer information',
    'customer_full_name_detail': 'Customer Full Name',
    'customer_email': 'Customer Email',
    'customer_phone': 'Customer Phone',
    'customer_address': 'Customer Address',
    'customer_notes': 'Customer Notes',
    'identity_personal': 'Identity & Personal',
    'financial_info': 'Financial Information',
    'files_attachments': 'Files & Attachments',
    'trip_history': 'Trip History',
    
    // Expenses
    'add_expense': 'Add Expense',
    'expense_description': 'Expense Description',
    'expense_amount': 'Expense Amount',
    'expense_category': 'Expense Category',
    'expense_date': 'Expense Date',
    'edit_expense': 'Edit Expense',
    'delete_expense': 'Delete Expense',
    'no_expenses': 'No expenses recorded',
    
    // Trip Overview
    'trip_overview': 'Trip Overview',
    'financials': 'Financials',
    'trip_status': 'Trip Status',
    'trip_destination': 'Trip Destination',
    'trip_dates': 'Trip Dates',
    'customer_stats': 'Customer Stats',
    'backend_data_status': 'Backend Data Status',
    'loaded': 'Loaded',
    'missing': 'Missing',
    
    // Additional Common Terms
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'export': 'Export',
    'import': 'Import',
    'print': 'Print',
    'download': 'Download',
    'upload': 'Upload',
    'submit': 'Submit',
    'reset': 'Reset',
    'clear': 'Clear',
    'apply': 'Apply',
    'approve': 'Approve',
    'reject': 'Reject',
    'pending_approval': 'Pending Approval',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'draft': 'Draft',
    'published': 'Published',
    'archived': 'Archived',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'online': 'Online',
    'offline': 'Offline',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'yes': 'Yes',
    'no': 'No',
    'true': 'True',
    'false': 'False',
    'all': 'All',
    'none': 'None',
    'select_all': 'Select All',
    'deselect_all': 'Deselect All',
    'expand_all': 'Expand All',
    'collapse_all': 'Collapse All',
    'show_more': 'Show More',
    'show_less': 'Show Less',
    'next': 'Next',
    'previous': 'Previous',
    'first': 'First',
    'last': 'Last',
    'page': 'Page',
    'of': 'of',
    'total': 'Total',
    'subtotal': 'Subtotal',
    'grand_total': 'Grand Total',
    'balance': 'Balance',
    'remaining': 'Remaining',
    'due': 'Due',
    'overdue': 'Overdue',
    'paid': 'Paid',
    'unpaid': 'Unpaid',
    'partial': 'Partial',
    'full': 'Full',
    'empty': 'Empty',
    'not_found': 'Not Found',
    'not_available': 'Not Available',
    'coming_soon': 'Coming Soon',
    'under_construction': 'Under Construction',
    'maintenance': 'Maintenance',
    'system_error': 'System Error',
    'network_error': 'Network Error',
    'connection_failed': 'Connection Failed',
    'timeout': 'Timeout',
    'retry': 'Retry',
    'try_again': 'Try Again',
  },
  zh: {
    // Navigation & Tabs
    'dashboard': '仪表板',
    'customers': '客户',
    'agents': '代理',
    'staff': '员工',
    'projects': '项目',
    'data': '数据',
    'checkinout': '签到/签退',
    'boss': '老板',
    'trips': '行程',
    'trip_details': '行程详情',
    'expenses': '费用',
    'transactions': '交易',
    'sharing': '分成',
    'reports': '报告',
    'settings': '设置',
    
    // Trip Management
    'project_management': '项目管理',
    'back_to_trips': '返回行程',
    'view_in': '查看币种:',
    'total_rolling': '总流水',
    'total_win_loss': '总输赢',
    'total_buy_in': '总买入',
    'total_buy_out': '总买出',
    'net_result': '净结果',
    'total_expenses': '总费用',
    'active_customers': '活跃客户',
    'recent_activity': '最近活动',
    
    // Actions
    'refresh': '刷新',
    'add_new': '新增',
    'edit': '编辑',
    'delete': '删除',
    'save': '保存',
    'cancel': '取消',
    'confirm': '确认',
    'close': '关闭',
    
    // Status
    'active': '活跃',
    'completed': '已完成',
    'in_progress': '进行中',
    'cancelled': '已取消',
    'pending': '待处理',
    
    // Common
    'name': '名称',
    'description': '描述',
    'date': '日期',
    'amount': '金额',
    'status': '状态',
    'actions': '操作',
    'loading': '加载中...',
    'error': '错误',
    'success': '成功',
    'no_data': '暂无数据',
    
    // Currency
    'currency': '币种',
    'exchange_rate': '汇率',
    'hkd': '港币',
    'myr': '马币',
    'peso': '比索',
    
    // Reports
    'reports_title': '实时报告仪表板',
    'reports_subtitle': '全面的商业智能和分析',
    'overview_metrics': '概览指标',
    'financial_summary': '财务摘要',
    'customer_metrics': '客户指标',
    'agent_performance': '代理表现',
    'operational_metrics': '运营指标',
    'agent_hierarchy': '代理表现层级',
    'agent_hierarchy_desc': '代理和客户的层级视图 - 展开查看客户详情',
    'sort_by': '排序方式:',
    'reports_total_rolling': '总流水',
    'win_loss': '输赢',
    'customer_count': '客户数量',
    'average_rolling': '平均流水',
    'agent_name': '代理姓名',
    'individual_rolling': '个人流水',
    'individual_win': '个人输赢',
    'trip_count': '行程数量',
    'profit_loss': '盈亏',
    'house_gross_win': '庄家毛利',
    'house_net_win': '庄家净利',
    'house_final_profit': '庄家最终利润',
    'reports_total_customers': '总客户数',
    'reports_active_customers': '活跃客户',
    'total_agents': '总代理数',
    'active_agents': '活跃代理',
    'total_trips': '总行程数',
    'completed_trips': '已完成行程',
    'ongoing_trips': '进行中行程',
    'profit_margin': '利润率',
    'rolling_percentage': '流水百分比',
    'company_share': '公司分成',
    'net_cash_flow': '净现金流',
    'real_time_sync': '实时同步',
    'last_sync': '最后同步',
    'connection_status': '连接状态',
    'connected': '已连接',
    'disconnected': '已断开',
    'sync_error': '同步错误',
    'auto_refresh': '自动刷新',
    'manual_refresh': '手动刷新',
    'export_data': '导出数据',
    
    // Financial Overview
    'financial_overview': '实时财务概览',
    'total_rolling_amount': '总流水金额',
    'company_gross_profit': '公司毛利',
    'overview_expenses': '费用',
    'company_net_profit': '公司净利润',
    'from_rolling_records': '来自客户流水记录',
    'from_trip_sharing': '来自行程分成数据',
    'total_operational_expenses': '行程分成的总运营费用',
    'company_share_from_trip': '行程分成的公司份额',
    
    // Operations Overview
    'operations_overview': '运营概览',
    'overview_active_customers': '活跃客户',
    'overview_active_agents': '活跃代理',
    'overview_trip_summary': '行程摘要',
    'overview_recent_activity': '最近活动',
    'of_total_customers': '总客户数',
    'of_total_agents': '总代理数',
    'completed_ongoing_planned': '已完成，进行中，计划中',
    'transactions_in_last_hours': '过去24小时交易',
    
    // Active Trips
    'overview_active_trips': '活跃行程',
    'current_ongoing_trips': '当前进行中的行程及实时表现数据',
    'testing_trip': '测试行程',
    'manila_okada': '马尼拉奥卡达',
    'overview_progress': '进度',
    'overview_rolling': '流水',
    'overview_win_loss': '输赢',
    
    // Customer Performance
    'customer_performance': '实时客户表现',
    'all_customers_based_on': '基于实时流水数据的所有客户',
    'sort_by_rolling': '排序方式：流水',
    'agent_active': '代理：• 活跃',
    'overview_commission_rate': '佣金率',
    
    // Additional Common Terms
    'welcome_user': '欢迎',
    'silver_vip': '银卡',
    'gold_vip': '金卡',
    'platinum_vip': '白金卡',
    'diamond_vip': '钻石卡',
    
    // Dashboard specific terms
    'company_loss': '公司输钱',
    'company_win': '公司赢钱',
    'break_even': '持平',
    'agent': '代理',
    'unknown_destination': '未知目的地',
    'progress': '进度',
    
    // Customer Management specific
    'update_customer_info': '更新基本客户信息',
    'add_customer_desc': '添加新客户的基本详情。创建后可以添加扩展详情。',
    'customer_full_name': '客户全名',
    'select_agent': '选择代理',
    'no_customers_found': '未找到客户',
    'contact_admin': '联系管理员添加客户',
    'add_first_customer': '添加您的第一个客户开始使用',
    'records': '记录',
    'live_data': '实时数据',
    'customer_since': '客户注册时间',
    'details_available': '详情可用',
    'no_details_available': '无详情可用',
    'edit_basic_info': '编辑基本信息',
    'edit_details': '编辑详情',
    'promote_to_agent': '提升为代理',
    'delete_customer': '删除客户',
    
    // Project Management specific
    'trips_loaded': '已加载行程',
    'customers_available': '可用客户', 
    'agents_available': '可用代理',
    'create_trip': '创建行程',
    'create_new_trip': '创建新行程',
    'create_trip_desc': '创建一个新行程，将保存到 Supabase 数据库。',
    'trip_name': '行程名称',
    'start_date': '开始日期',
    'end_date': '结束日期',
    'creating': '创建中...',
    'loading_trips': '加载行程中...',
    'no_trips_found': '未找到行程',
    'view_details': '查看详情',
    'amount_hkd': '金额 (港币)',
    'buy_in': '买入',
    'buy_out': '买出',
    
    // Additional Project Management
    'trip_customers': '行程客户',
    'add_customer': '添加客户',
    'add_customer_to_trip': '添加客户到行程',
    'search_select_customers': '搜索并选择可用客户',
    'search_customers': '搜索客户',
    'search_by_name_email_agent': '按姓名、邮箱或代理搜索...',
    'showing_customers': '显示',
    'of_available_customers': '个可用客户',
    'add_first_customer_trip': '添加第一个客户',
    'no_customers_added': '此行程未添加客户',
    'all_customers_added': '所有客户已添加到此行程',
    'no_customers_match_search': '没有客户匹配您的搜索',
    'adding': '添加中...',
    'add': '添加',
    'deleting': '删除中...',
    'delete_customer_confirm': '删除客户',
    'delete_customer_warning': '确定要从行程中移除此客户吗？此操作无法撤销。',
    'remove_from_trip': '从行程中移除',
    
    // Financial Terms
    'cash_out': '现金出',
    'rolling': '流水',
    'rolling_amount': '流水金额',
    'commission_earned': '佣金收入',
    'profit_sharing_rate': '利润分成率',
    'agent_profit_sharing': '代理利润分成',
    'agent_summary': '代理摘要',
    'company_share_amount': '公司分成',
    'agent_share_amount': '代理分成',
    'total_commission_amount': '总佣金',
    'total_profit_amount': '总利润',
    'agent_profit_share_amount': '代理利润分成',
    'customer_count_total': '客户数量',
    
    // Transaction Management
    'add_transaction': '添加交易',
    'add_rolling': '添加流水',
    'transaction_type': '交易类型',
    'transaction_amount': '交易金额',
    'commission_rate': '佣金率',
    'current_rate': '当前费率',
    'commission': '佣金',
    'game_type': '游戏类型',
    'venue': '场地',
    'date_time': '日期时间',
    'attachment': '附件',
    'optional': '可选',
    'required': '必填',
    'enter_amount': '输入金额',
    'select_game_type': '选择游戏类型',
    'enter_venue': '输入场地',
    'select_date_time': '选择日期和时间',
    'upload_attachment': '上传附件',
    
    // History and Records
    'transaction_history': '交易历史',
    'rolling_history': '流水历史',
    'no_transaction_history': '无交易历史',
    'no_rolling_history': '无流水历史',
    'edit_transaction': '编辑交易',
    'edit_rolling': '编辑流水',
    'delete_transaction': '删除交易',
    'delete_rolling': '删除流水',
    'confirm_delete_transaction': '确定要删除此交易吗？',
    'confirm_delete_rolling': '确定要删除此流水记录吗？',
    
    // Photos and Attachments
    'photos': '照片',
    'view_customer_photos': '查看客户照片',
    'transaction_photos': '交易照片',
    'rolling_photos': '流水照片',
    'upload_photo': '上传照片',
    'no_photos': '无照片可用',
    
    // VIP Levels
    'vip': 'VIP',
    'vip_level': 'VIP等级',
    'standard': '标准',
    'silver': '银卡',
    'gold': '金卡',
    'platinum': '白金卡',
    'diamond': '钻石卡',
    
    // Profit Sharing
    'profit_sharing': '利润分成',
    'profit_sharing_information': '利润分成信息',
    'edit_profit_sharing': '编辑利润分成',
    'update_profit_sharing': '更新利润分成',
    'new_profit_sharing_rate': '新利润分成率',
    'current_profit_sharing_rate': '当前利润分成率',
    'projected_profit_share': '预计利润分成',
    'rate_change_impact': '费率变化影响',
    
    // Customer Details
    'edit_customer_details': '编辑客户详情',
    'update_comprehensive_info': '更新全面的客户信息',
    'customer_full_name_detail': '客户全名',
    'customer_email': '客户邮箱',
    'customer_phone': '客户电话',
    'customer_address': '客户地址',
    'customer_notes': '客户备注',
    'identity_personal': '身份和个人信息',
    'financial_info': '财务信息',
    'files_attachments': '文件和附件',
    'trip_history': '行程历史',
    
    // Expenses
    'add_expense': '添加费用',
    'expense_description': '费用描述',
    'expense_amount': '费用金额',
    'expense_category': '费用类别',
    'expense_date': '费用日期',
    'edit_expense': '编辑费用',
    'delete_expense': '删除费用',
    'no_expenses': '无费用记录',
    
    // Trip Overview
    'trip_overview': '行程概览',
    'financials': '财务',
    'trip_status': '行程状态',
    'trip_destination': '行程目的地',
    'trip_dates': '行程日期',
    'customer_stats': '客户统计',
    'backend_data_status': '后端数据状态',
    'loaded': '已加载',
    'missing': '缺失',
    
    // Additional Common Terms
    'search': '搜索',
    'filter': '筛选',
    'sort': '排序',
    'export': '导出',
    'import': '导入',
    'print': '打印',
    'download': '下载',
    'upload': '上传',
    'submit': '提交',
    'reset': '重置',
    'clear': '清除',
    'apply': '应用',
    'approve': '批准',
    'reject': '拒绝',
    'pending_approval': '待批准',
    'approved': '已批准',
    'rejected': '已拒绝',
    'draft': '草稿',
    'published': '已发布',
    'archived': '已归档',
    'enabled': '已启用',
    'disabled': '已禁用',
    'online': '在线',
    'offline': '离线',
    'available': '可用',
    'unavailable': '不可用',
    'yes': '是',
    'no': '否',
    'true': '真',
    'false': '假',
    'all': '全部',
    'none': '无',
    'select_all': '全选',
    'deselect_all': '取消全选',
    'expand_all': '全部展开',
    'collapse_all': '全部收起',
    'show_more': '显示更多',
    'show_less': '显示更少',
    'next': '下一页',
    'previous': '上一页',
    'first': '首页',
    'last': '末页',
    'page': '页',
    'of': '共',
    'total': '总计',
    'subtotal': '小计',
    'grand_total': '总计',
    'balance': '余额',
    'remaining': '剩余',
    'due': '到期',
    'overdue': '逾期',
    'paid': '已付',
    'unpaid': '未付',
    'partial': '部分',
    'full': '完整',
    'empty': '空',
    'not_found': '未找到',
    'not_available': '不可用',
    'coming_soon': '即将推出',
    'under_construction': '建设中',
    'maintenance': '维护中',
    'system_error': '系统错误',
    'network_error': '网络错误',
    'connection_failed': '连接失败',
    'timeout': '超时',
    'retry': '重试',
    'try_again': '再试一次',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 从 localStorage 获取保存的语言设置，默认为英文
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  // 保存语言设置到 localStorage
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  // 翻译函数
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
